//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PandemicRole.Infrastructure.Globalization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_es {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_es() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PandemicRole.Infrastructure.Globalization.Localization.es", typeof(Localization_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Role_1 {
            get {
                return ResourceManager.GetString("Role_1", resourceCulture);
            }
        }
        
        internal static string Role_2 {
            get {
                return ResourceManager.GetString("Role_2", resourceCulture);
            }
        }
        
        internal static string Role_3 {
            get {
                return ResourceManager.GetString("Role_3", resourceCulture);
            }
        }
        
        internal static string Role_4 {
            get {
                return ResourceManager.GetString("Role_4", resourceCulture);
            }
        }
        
        internal static string Role_5 {
            get {
                return ResourceManager.GetString("Role_5", resourceCulture);
            }
        }
        
        internal static string Role_6 {
            get {
                return ResourceManager.GetString("Role_6", resourceCulture);
            }
        }
        
        internal static string Role_7 {
            get {
                return ResourceManager.GetString("Role_7", resourceCulture);
            }
        }
        
        internal static string Role_8 {
            get {
                return ResourceManager.GetString("Role_8", resourceCulture);
            }
        }
        
        internal static string Role_9 {
            get {
                return ResourceManager.GetString("Role_9", resourceCulture);
            }
        }
        
        internal static string Role_10 {
            get {
                return ResourceManager.GetString("Role_10", resourceCulture);
            }
        }
        
        internal static string Role_11 {
            get {
                return ResourceManager.GetString("Role_11", resourceCulture);
            }
        }
        
        internal static string Role_12 {
            get {
                return ResourceManager.GetString("Role_12", resourceCulture);
            }
        }
        
        internal static string Role_13 {
            get {
                return ResourceManager.GetString("Role_13", resourceCulture);
            }
        }
        
        internal static string Role_14 {
            get {
                return ResourceManager.GetString("Role_14", resourceCulture);
            }
        }
        
        internal static string Role_15 {
            get {
                return ResourceManager.GetString("Role_15", resourceCulture);
            }
        }
        
        internal static string Role_16 {
            get {
                return ResourceManager.GetString("Role_16", resourceCulture);
            }
        }
        
        internal static string Role_17 {
            get {
                return ResourceManager.GetString("Role_17", resourceCulture);
            }
        }
        
        internal static string Role_18 {
            get {
                return ResourceManager.GetString("Role_18", resourceCulture);
            }
        }
        
        internal static string Role_19 {
            get {
                return ResourceManager.GetString("Role_19", resourceCulture);
            }
        }
        
        internal static string Role_20 {
            get {
                return ResourceManager.GetString("Role_20", resourceCulture);
            }
        }
        
        internal static string Role_21 {
            get {
                return ResourceManager.GetString("Role_21", resourceCulture);
            }
        }
        
        internal static string Role_22 {
            get {
                return ResourceManager.GetString("Role_22", resourceCulture);
            }
        }
        
        internal static string Role_23 {
            get {
                return ResourceManager.GetString("Role_23", resourceCulture);
            }
        }
        
        internal static string Role_24 {
            get {
                return ResourceManager.GetString("Role_24", resourceCulture);
            }
        }
        
        internal static string Role_25 {
            get {
                return ResourceManager.GetString("Role_25", resourceCulture);
            }
        }
        
        internal static string Role_26 {
            get {
                return ResourceManager.GetString("Role_26", resourceCulture);
            }
        }
        
        internal static string Role_27 {
            get {
                return ResourceManager.GetString("Role_27", resourceCulture);
            }
        }
        
        internal static string Role_28 {
            get {
                return ResourceManager.GetString("Role_28", resourceCulture);
            }
        }
        
        internal static string Role_29 {
            get {
                return ResourceManager.GetString("Role_29", resourceCulture);
            }
        }
        
        internal static string Role_30 {
            get {
                return ResourceManager.GetString("Role_30", resourceCulture);
            }
        }
        
        internal static string Role_31 {
            get {
                return ResourceManager.GetString("Role_31", resourceCulture);
            }
        }
        
        internal static string Role_32 {
            get {
                return ResourceManager.GetString("Role_32", resourceCulture);
            }
        }
        
        internal static string Role_33 {
            get {
                return ResourceManager.GetString("Role_33", resourceCulture);
            }
        }
        
        internal static string Role_34 {
            get {
                return ResourceManager.GetString("Role_34", resourceCulture);
            }
        }
        
        internal static string Role_35 {
            get {
                return ResourceManager.GetString("Role_35", resourceCulture);
            }
        }
        
        internal static string Role_36 {
            get {
                return ResourceManager.GetString("Role_36", resourceCulture);
            }
        }
        
        internal static string Role_37 {
            get {
                return ResourceManager.GetString("Role_37", resourceCulture);
            }
        }
        
        internal static string Role_38 {
            get {
                return ResourceManager.GetString("Role_38", resourceCulture);
            }
        }
        
        internal static string Role_39 {
            get {
                return ResourceManager.GetString("Role_39", resourceCulture);
            }
        }
        
        internal static string Role_40 {
            get {
                return ResourceManager.GetString("Role_40", resourceCulture);
            }
        }
        
        internal static string Role_41 {
            get {
                return ResourceManager.GetString("Role_41", resourceCulture);
            }
        }
        
        internal static string Role_42 {
            get {
                return ResourceManager.GetString("Role_42", resourceCulture);
            }
        }
        
        internal static string Role_43 {
            get {
                return ResourceManager.GetString("Role_43", resourceCulture);
            }
        }
        
        internal static string Role_44 {
            get {
                return ResourceManager.GetString("Role_44", resourceCulture);
            }
        }
        
        internal static string Role_45 {
            get {
                return ResourceManager.GetString("Role_45", resourceCulture);
            }
        }
        
        internal static string Role_46 {
            get {
                return ResourceManager.GetString("Role_46", resourceCulture);
            }
        }
        
        internal static string Role_47 {
            get {
                return ResourceManager.GetString("Role_47", resourceCulture);
            }
        }
        
        internal static string Role_48 {
            get {
                return ResourceManager.GetString("Role_48", resourceCulture);
            }
        }
        
        internal static string Role_49 {
            get {
                return ResourceManager.GetString("Role_49", resourceCulture);
            }
        }
        
        internal static string Role_50 {
            get {
                return ResourceManager.GetString("Role_50", resourceCulture);
            }
        }
        
        internal static string Role_51 {
            get {
                return ResourceManager.GetString("Role_51", resourceCulture);
            }
        }
        
        internal static string Role_52 {
            get {
                return ResourceManager.GetString("Role_52", resourceCulture);
            }
        }
        
        internal static string Role_53 {
            get {
                return ResourceManager.GetString("Role_53", resourceCulture);
            }
        }
        
        internal static string Role_54 {
            get {
                return ResourceManager.GetString("Role_54", resourceCulture);
            }
        }
        
        internal static string Role_55 {
            get {
                return ResourceManager.GetString("Role_55", resourceCulture);
            }
        }
        
        internal static string Role_56 {
            get {
                return ResourceManager.GetString("Role_56", resourceCulture);
            }
        }
        
        internal static string Role_57 {
            get {
                return ResourceManager.GetString("Role_57", resourceCulture);
            }
        }
        
        internal static string Role_58 {
            get {
                return ResourceManager.GetString("Role_58", resourceCulture);
            }
        }
        
        internal static string Role_59 {
            get {
                return ResourceManager.GetString("Role_59", resourceCulture);
            }
        }
        
        internal static string Role_60 {
            get {
                return ResourceManager.GetString("Role_60", resourceCulture);
            }
        }
        
        internal static string Role_61 {
            get {
                return ResourceManager.GetString("Role_61", resourceCulture);
            }
        }
        
        internal static string Role_62 {
            get {
                return ResourceManager.GetString("Role_62", resourceCulture);
            }
        }
        
        internal static string Role_63 {
            get {
                return ResourceManager.GetString("Role_63", resourceCulture);
            }
        }
        
        internal static string Role_64 {
            get {
                return ResourceManager.GetString("Role_64", resourceCulture);
            }
        }
        
        internal static string Role_65 {
            get {
                return ResourceManager.GetString("Role_65", resourceCulture);
            }
        }
        
        internal static string Role_66 {
            get {
                return ResourceManager.GetString("Role_66", resourceCulture);
            }
        }
        
        internal static string Role_67 {
            get {
                return ResourceManager.GetString("Role_67", resourceCulture);
            }
        }
        
        internal static string Role_68 {
            get {
                return ResourceManager.GetString("Role_68", resourceCulture);
            }
        }
        
        internal static string Role_69 {
            get {
                return ResourceManager.GetString("Role_69", resourceCulture);
            }
        }
        
        internal static string Role_70 {
            get {
                return ResourceManager.GetString("Role_70", resourceCulture);
            }
        }
        
        internal static string Role_71 {
            get {
                return ResourceManager.GetString("Role_71", resourceCulture);
            }
        }
        
        internal static string Role_72 {
            get {
                return ResourceManager.GetString("Role_72", resourceCulture);
            }
        }
        
        internal static string Role_73 {
            get {
                return ResourceManager.GetString("Role_73", resourceCulture);
            }
        }
        
        internal static string Role_74 {
            get {
                return ResourceManager.GetString("Role_74", resourceCulture);
            }
        }
        
        internal static string Role_75 {
            get {
                return ResourceManager.GetString("Role_75", resourceCulture);
            }
        }
        
        internal static string Role_76 {
            get {
                return ResourceManager.GetString("Role_76", resourceCulture);
            }
        }
        
        internal static string Role_77 {
            get {
                return ResourceManager.GetString("Role_77", resourceCulture);
            }
        }
        
        internal static string Role_78 {
            get {
                return ResourceManager.GetString("Role_78", resourceCulture);
            }
        }
        
        internal static string Role_79 {
            get {
                return ResourceManager.GetString("Role_79", resourceCulture);
            }
        }
        
        internal static string Role_80 {
            get {
                return ResourceManager.GetString("Role_80", resourceCulture);
            }
        }
        
        internal static string Role_81 {
            get {
                return ResourceManager.GetString("Role_81", resourceCulture);
            }
        }
        
        internal static string Role_82 {
            get {
                return ResourceManager.GetString("Role_82", resourceCulture);
            }
        }
        
        internal static string Role_83 {
            get {
                return ResourceManager.GetString("Role_83", resourceCulture);
            }
        }
        
        internal static string Role_84 {
            get {
                return ResourceManager.GetString("Role_84", resourceCulture);
            }
        }
        
        internal static string Role_85 {
            get {
                return ResourceManager.GetString("Role_85", resourceCulture);
            }
        }
        
        internal static string Role_86 {
            get {
                return ResourceManager.GetString("Role_86", resourceCulture);
            }
        }
        
        internal static string Role_87 {
            get {
                return ResourceManager.GetString("Role_87", resourceCulture);
            }
        }
        
        internal static string Role_88 {
            get {
                return ResourceManager.GetString("Role_88", resourceCulture);
            }
        }
        
        internal static string Role_89 {
            get {
                return ResourceManager.GetString("Role_89", resourceCulture);
            }
        }
        
        internal static string Role_90 {
            get {
                return ResourceManager.GetString("Role_90", resourceCulture);
            }
        }
        
        internal static string Role_1_Description {
            get {
                return ResourceManager.GetString("Role_1_Description", resourceCulture);
            }
        }
        
        internal static string Role_2_Description {
            get {
                return ResourceManager.GetString("Role_2_Description", resourceCulture);
            }
        }
        
        internal static string Role_3_Description {
            get {
                return ResourceManager.GetString("Role_3_Description", resourceCulture);
            }
        }
        
        internal static string Role_4_Description {
            get {
                return ResourceManager.GetString("Role_4_Description", resourceCulture);
            }
        }
        
        internal static string Role_5_Description {
            get {
                return ResourceManager.GetString("Role_5_Description", resourceCulture);
            }
        }
        
        internal static string Role_6_Description {
            get {
                return ResourceManager.GetString("Role_6_Description", resourceCulture);
            }
        }
        
        internal static string Role_7_Description {
            get {
                return ResourceManager.GetString("Role_7_Description", resourceCulture);
            }
        }
        
        internal static string Role_8_Description {
            get {
                return ResourceManager.GetString("Role_8_Description", resourceCulture);
            }
        }
        
        internal static string Role_9_Description {
            get {
                return ResourceManager.GetString("Role_9_Description", resourceCulture);
            }
        }
        
        internal static string Role_10_Description {
            get {
                return ResourceManager.GetString("Role_10_Description", resourceCulture);
            }
        }
        
        internal static string Role_11_Description {
            get {
                return ResourceManager.GetString("Role_11_Description", resourceCulture);
            }
        }
        
        internal static string Role_12_Description {
            get {
                return ResourceManager.GetString("Role_12_Description", resourceCulture);
            }
        }
        
        internal static string Role_13_Description {
            get {
                return ResourceManager.GetString("Role_13_Description", resourceCulture);
            }
        }
        
        internal static string Role_14_Description {
            get {
                return ResourceManager.GetString("Role_14_Description", resourceCulture);
            }
        }
        
        internal static string Role_15_Description {
            get {
                return ResourceManager.GetString("Role_15_Description", resourceCulture);
            }
        }
        
        internal static string Role_16_Description {
            get {
                return ResourceManager.GetString("Role_16_Description", resourceCulture);
            }
        }
        
        internal static string Role_17_Description {
            get {
                return ResourceManager.GetString("Role_17_Description", resourceCulture);
            }
        }
        
        internal static string Role_18_Description {
            get {
                return ResourceManager.GetString("Role_18_Description", resourceCulture);
            }
        }
        
        internal static string Role_19_Description {
            get {
                return ResourceManager.GetString("Role_19_Description", resourceCulture);
            }
        }
        
        internal static string Role_20_Description {
            get {
                return ResourceManager.GetString("Role_20_Description", resourceCulture);
            }
        }
        
        internal static string Role_21_Description {
            get {
                return ResourceManager.GetString("Role_21_Description", resourceCulture);
            }
        }
        
        internal static string Role_22_Description {
            get {
                return ResourceManager.GetString("Role_22_Description", resourceCulture);
            }
        }
        
        internal static string Role_23_Description {
            get {
                return ResourceManager.GetString("Role_23_Description", resourceCulture);
            }
        }
        
        internal static string Role_24_Description {
            get {
                return ResourceManager.GetString("Role_24_Description", resourceCulture);
            }
        }
        
        internal static string Role_25_Description {
            get {
                return ResourceManager.GetString("Role_25_Description", resourceCulture);
            }
        }
        
        internal static string Role_26_Description {
            get {
                return ResourceManager.GetString("Role_26_Description", resourceCulture);
            }
        }
        
        internal static string Role_27_Description {
            get {
                return ResourceManager.GetString("Role_27_Description", resourceCulture);
            }
        }
        
        internal static string Role_28_Description {
            get {
                return ResourceManager.GetString("Role_28_Description", resourceCulture);
            }
        }
        
        internal static string Role_29_Description {
            get {
                return ResourceManager.GetString("Role_29_Description", resourceCulture);
            }
        }
        
        internal static string Role_30_Description {
            get {
                return ResourceManager.GetString("Role_30_Description", resourceCulture);
            }
        }
        
        internal static string Role_31_Description {
            get {
                return ResourceManager.GetString("Role_31_Description", resourceCulture);
            }
        }
        
        internal static string Role_32_Description {
            get {
                return ResourceManager.GetString("Role_32_Description", resourceCulture);
            }
        }
        
        internal static string Role_33_Description {
            get {
                return ResourceManager.GetString("Role_33_Description", resourceCulture);
            }
        }
        
        internal static string Role_34_Description {
            get {
                return ResourceManager.GetString("Role_34_Description", resourceCulture);
            }
        }
        
        internal static string Role_35_Description {
            get {
                return ResourceManager.GetString("Role_35_Description", resourceCulture);
            }
        }
        
        internal static string Role_36_Description {
            get {
                return ResourceManager.GetString("Role_36_Description", resourceCulture);
            }
        }
        
        internal static string Role_37_Description {
            get {
                return ResourceManager.GetString("Role_37_Description", resourceCulture);
            }
        }
        
        internal static string Role_38_Description {
            get {
                return ResourceManager.GetString("Role_38_Description", resourceCulture);
            }
        }
        
        internal static string Role_39_Description {
            get {
                return ResourceManager.GetString("Role_39_Description", resourceCulture);
            }
        }
        
        internal static string Role_40_Description {
            get {
                return ResourceManager.GetString("Role_40_Description", resourceCulture);
            }
        }
        
        internal static string Role_41_Description {
            get {
                return ResourceManager.GetString("Role_41_Description", resourceCulture);
            }
        }
        
        internal static string Role_42_Description {
            get {
                return ResourceManager.GetString("Role_42_Description", resourceCulture);
            }
        }
        
        internal static string Role_43_Description {
            get {
                return ResourceManager.GetString("Role_43_Description", resourceCulture);
            }
        }
        
        internal static string Role_44_Description {
            get {
                return ResourceManager.GetString("Role_44_Description", resourceCulture);
            }
        }
        
        internal static string Role_45_Description {
            get {
                return ResourceManager.GetString("Role_45_Description", resourceCulture);
            }
        }
        
        internal static string Role_46_Description {
            get {
                return ResourceManager.GetString("Role_46_Description", resourceCulture);
            }
        }
        
        internal static string Role_47_Description {
            get {
                return ResourceManager.GetString("Role_47_Description", resourceCulture);
            }
        }
        
        internal static string Role_48_Description {
            get {
                return ResourceManager.GetString("Role_48_Description", resourceCulture);
            }
        }
        
        internal static string Role_49_Description {
            get {
                return ResourceManager.GetString("Role_49_Description", resourceCulture);
            }
        }
        
        internal static string Role_50_Description {
            get {
                return ResourceManager.GetString("Role_50_Description", resourceCulture);
            }
        }
        
        internal static string Role_51_Description {
            get {
                return ResourceManager.GetString("Role_51_Description", resourceCulture);
            }
        }
        
        internal static string Role_52_Description {
            get {
                return ResourceManager.GetString("Role_52_Description", resourceCulture);
            }
        }
        
        internal static string Role_53_Description {
            get {
                return ResourceManager.GetString("Role_53_Description", resourceCulture);
            }
        }
        
        internal static string Role_54_Description {
            get {
                return ResourceManager.GetString("Role_54_Description", resourceCulture);
            }
        }
        
        internal static string Role_55_Description {
            get {
                return ResourceManager.GetString("Role_55_Description", resourceCulture);
            }
        }
        
        internal static string Role_56_Description {
            get {
                return ResourceManager.GetString("Role_56_Description", resourceCulture);
            }
        }
        
        internal static string Role_57_Description {
            get {
                return ResourceManager.GetString("Role_57_Description", resourceCulture);
            }
        }
        
        internal static string Role_58_Description {
            get {
                return ResourceManager.GetString("Role_58_Description", resourceCulture);
            }
        }
        
        internal static string Role_59_Description {
            get {
                return ResourceManager.GetString("Role_59_Description", resourceCulture);
            }
        }
        
        internal static string Role_60_Description {
            get {
                return ResourceManager.GetString("Role_60_Description", resourceCulture);
            }
        }
        
        internal static string Role_61_Description {
            get {
                return ResourceManager.GetString("Role_61_Description", resourceCulture);
            }
        }
        
        internal static string Role_62_Description {
            get {
                return ResourceManager.GetString("Role_62_Description", resourceCulture);
            }
        }
        
        internal static string Role_63_Description {
            get {
                return ResourceManager.GetString("Role_63_Description", resourceCulture);
            }
        }
        
        internal static string Role_64_Description {
            get {
                return ResourceManager.GetString("Role_64_Description", resourceCulture);
            }
        }
        
        internal static string Role_65_Description {
            get {
                return ResourceManager.GetString("Role_65_Description", resourceCulture);
            }
        }
        
        internal static string Role_66_Description {
            get {
                return ResourceManager.GetString("Role_66_Description", resourceCulture);
            }
        }
        
        internal static string Role_67_Description {
            get {
                return ResourceManager.GetString("Role_67_Description", resourceCulture);
            }
        }
        
        internal static string Role_68_Description {
            get {
                return ResourceManager.GetString("Role_68_Description", resourceCulture);
            }
        }
        
        internal static string Role_69_Description {
            get {
                return ResourceManager.GetString("Role_69_Description", resourceCulture);
            }
        }
        
        internal static string Role_70_Description {
            get {
                return ResourceManager.GetString("Role_70_Description", resourceCulture);
            }
        }
        
        internal static string Role_71_Description {
            get {
                return ResourceManager.GetString("Role_71_Description", resourceCulture);
            }
        }
        
        internal static string Role_72_Description {
            get {
                return ResourceManager.GetString("Role_72_Description", resourceCulture);
            }
        }
        
        internal static string Role_73_Description {
            get {
                return ResourceManager.GetString("Role_73_Description", resourceCulture);
            }
        }
        
        internal static string Role_74_Description {
            get {
                return ResourceManager.GetString("Role_74_Description", resourceCulture);
            }
        }
        
        internal static string Role_75_Description {
            get {
                return ResourceManager.GetString("Role_75_Description", resourceCulture);
            }
        }
        
        internal static string Role_76_Description {
            get {
                return ResourceManager.GetString("Role_76_Description", resourceCulture);
            }
        }
        
        internal static string Role_77_Description {
            get {
                return ResourceManager.GetString("Role_77_Description", resourceCulture);
            }
        }
        
        internal static string Role_78_Description {
            get {
                return ResourceManager.GetString("Role_78_Description", resourceCulture);
            }
        }
        
        internal static string Role_79_Description {
            get {
                return ResourceManager.GetString("Role_79_Description", resourceCulture);
            }
        }
        
        internal static string Role_80_Description {
            get {
                return ResourceManager.GetString("Role_80_Description", resourceCulture);
            }
        }
        
        internal static string Role_81_Description {
            get {
                return ResourceManager.GetString("Role_81_Description", resourceCulture);
            }
        }
        
        internal static string Role_82_Description {
            get {
                return ResourceManager.GetString("Role_82_Description", resourceCulture);
            }
        }
        
        internal static string Role_83_Description {
            get {
                return ResourceManager.GetString("Role_83_Description", resourceCulture);
            }
        }
        
        internal static string Role_84_Description {
            get {
                return ResourceManager.GetString("Role_84_Description", resourceCulture);
            }
        }
        
        internal static string Role_85_Description {
            get {
                return ResourceManager.GetString("Role_85_Description", resourceCulture);
            }
        }
        
        internal static string Role_86_Description {
            get {
                return ResourceManager.GetString("Role_86_Description", resourceCulture);
            }
        }
        
        internal static string Role_87_Description {
            get {
                return ResourceManager.GetString("Role_87_Description", resourceCulture);
            }
        }
        
        internal static string Role_88_Description {
            get {
                return ResourceManager.GetString("Role_88_Description", resourceCulture);
            }
        }
        
        internal static string Role_89_Description {
            get {
                return ResourceManager.GetString("Role_89_Description", resourceCulture);
            }
        }
        
        internal static string Role_90_Description {
            get {
                return ResourceManager.GetString("Role_90_Description", resourceCulture);
            }
        }
    }
}
